version: "3.9"
services:
  nemotron:
    image: vllm/vllm-openai:v0.10.1
    command: >
      vllm serve nvidia/NVIDIA-Nemotron-Nano-9B-v2
      --trust-remote-code
      --mamba_ssm_cache_dtype float32
      --enable-auto-tool-choice
      --tool-parser-plugin "NVIDIA-Nemotron-Nano-9B-v2/nemotron_toolcall_parser_no_streaming.py"
      --tool-call-parser "nemotron_json"
    ports:
      - "8000:8000"
    volumes:
      - ./NVIDIA-Nemotron-Nano-9B-v2:/model

  api:
    build: .
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 5000
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - nemotron
